# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\prueba02.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import stmt
from PyQt5 import QtCore, QtGui, QtWidgets
import serial
from serial import Serial



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(615, 591)
        self.lcdNumber = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber.setGeometry(QtCore.QRect(150, 90, 151, 81))
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setProperty("intValue", 1)
        self.lcdNumber.setObjectName("lcdNumber")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

# User functions BEGIN

def getValues(value):
    print("empezar hilo")
    while isRun:
        
        cad = stm.readline().decode('ascii').strip()
        if cad:
            
            pos=cad.index(":")
            label = cad[:pos]
            value=cad[pos+1:]
            if label == 'adc':
                ui.lcdNumber.setProperty("intValue", value)
                print(value)

# User functions END

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    
    # User code begin

    # files begin
    file = open("prueba.txt", "w")

    file.write("Hola mundo\n")

    # files end
    hilo1 = threading.Thread(name="lecturaAdc",target=getValues,daemon=True, args=(1,))
    stm = serial.Serial("COM9",115200)
    isRun=True
    hilo1.start()
    # User code end

    sys.exit(app.exec_())
    
